name = "proxmox-frond"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[vars]
APP_ENV = "dev"

[[d1_databases]]
binding = "DB"
database_name = "proxmox-frond"
database_id = "REPLACE_WITH_D1_ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "proxmox-frond"
